Move cache purge to ci_hugo_build.yml (for now)

diff --git a/.github/workflows/ci_hugo_build.yml b/.github/workflows/ci_hugo_build.yml
--- a/.github/workflows/ci_hugo_build.yml
+++ b/.github/workflows/ci_hugo_build.yml
@@ -97,6 +97,7 @@ jobs:
             klakegg/hugo:${label} \
             --minify --i18n-warnings --gc --path-warnings --verbose --baseURL="https://wz2100.net/" --destination="/target"
       - name: Publish gh-pages
+        id: 'publish-pages'
         env:
           GITHUB_ACTOR: ${{ secrets.WZ2100_PUSH_USERNAME }}
           PUSH_PAT: ${{ secrets.WZ2100_PUSH_SECRET_TOKEN }} # use a PAT so that subsequent workflows are triggered on push
@@ -106,5 +107,85 @@ jobs:
           git config user.email "61424532+wzdev-ci@users.noreply.github.com"
           git add -A
           short_sha="$(echo ${GITHUB_SHA} | cut -c1-8)"
-          git commit -m "Deploy master branch: ${short_sha}" || exit 0
+          git commit -m "Deploy master branch: ${short_sha}" || echo "::set-output name=SKIPPED_DEPLOYMENT::true" && exit 0
+          # Get the new commit's SHA
+          NEW_COMMIT_SHA=$(git rev-parse --verify HEAD)
+          # Push the new commit to the gh-pages branch
           git push "https://${PUSH_PAT}@github.com/Warzone2100/wz2100.net.git" gh-pages:gh-pages
+          echo "::set-output name=SKIPPED_DEPLOYMENT::false"
+          echo "::set-output name=GH_PAGES_BRANCH_COMMIT_SHA::${NEW_COMMIT_SHA}"
+      - name: 'Wait for Deployment'
+        id: deployments
+        if: success() && (steps.publish-pages.outputs.SKIPPED_DEPLOYMENT == 'false')
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          GH_PAGES_BRANCH_COMMIT_SHA: ${{ steps.publish-pages.outputs.GH_PAGES_BRANCH_COMMIT_SHA }}
+        run: |
+          # Poll until we find a deployment with a sha == the push's commit's SHA
+          status=1
+          POLL_ATTEMPTS=0
+          while [ $POLL_ATTEMPTS -le 15 ]
+          do
+            sleep_interval=$(( POLL_ATTEMPTS * POLL_ATTEMPTS ))
+            sleep ${sleep_interval}
+            curl -H "Authorization: token ${GITHUB_TOKEN}" -s "https://api.github.com/repos/${GITHUB_REPOSITORY}/deployments" | jq --exit-status '.[] | select(.sha == "${GH_PAGES_BRANCH_COMMIT_SHA}" and .environment == "github-pages")' > "deployment.json"
+            status=$?
+            (( POLL_ATTEMPTS++ ))
+            if [ status -eq 0 ]; then
+              break
+            fi
+          done
+          if [ status -ne 0 ]; then
+            # Did not find matching deployment
+            echo "::error ::Failed to find matching deployment for: ${GITHUB_SHA}"
+            exit 1
+          fi
+          DEPLOYMENT_ID=$(cat "deployment.json" | jq --raw-output '.id')
+          if [ -z "$DEPLOYMENT_ID" ]; then
+            echo "::error ::Missing expected '.id' field"
+            exit 1
+          fi
+          echo "Found deployment ID: ${DEPLOYMENT_ID}"
+          echo "::set-output name=DEPLOYMENT_ID::${DEPLOYMENT_ID}"
+      - name: 'Wait for Deployment Success'
+        if: success() && (steps.publish-pages.outputs.SKIPPED_DEPLOYMENT == 'false')
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          DEPLOYMENT_ID: ${{ steps.deployments.outputs.DEPLOYMENT_ID }}
+        run: |
+          # Poll deployment statuses until we find a status with:
+          # "state": "success"
+          # "environment": "github-pages"
+          DEPLOYMENT_STATE=""
+          POLL_ATTEMPTS=0
+          while [ $POLL_ATTEMPTS -le 12 ]
+          do
+            sleep_interval=$(( POLL_ATTEMPTS * POLL_ATTEMPTS ))
+            sleep ${sleep_interval}
+            DEPLOYMENT_STATE=$(curl -H "Authorization: token ${GITHUB_TOKEN}" -s "https://api.github.com/repos/${GITHUB_REPOSITORY}/deployments/${DEPLOYMENT_ID}/statuses" | jq --raw-output --exit-status --argjson end_states '["success","error","failure"]' '.[] | select( (.state as $state | $end_states | index($state) != null ) and (.environment == "github-pages") ) | .state')
+            status=$?
+            (( POLL_ATTEMPTS++ ))
+            if [ status -eq 0 ]; then
+              break
+            fi
+          done
+          if [ status -ne 0 ]; then
+            # Did not find matching deployment
+            echo "::error ::Deployment did not finish before timeout"
+            exit 1
+          fi
+          echo "Found deployment state: ${DEPLOYMENT_STATE}"
+          if [ "$DEPLOYMENT_STATE" != "success" ]; then
+            echo "::error ::Deployment did not appear to succeed? (state: ${DEPLOYMENT_STATE})"
+            exit 1
+          fi
+      - name: 'Purge Cloudflare Cache'
+        if: success() && (steps.publish-pages.outputs.SKIPPED_DEPLOYMENT == 'false')
+        env:
+          CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_WZ2100_ZONE }}
+          CLOUDFLARE_CACHEPURGE_TOKEN: ${{ secrets.CLOUDFLARE_WZ2100_CACHEPURGE_TOKEN }}
+        run: |
+          curl -X POST "https://api.cloudflare.com/client/v4/zones/${CLOUDFLARE_ZONE}/purge_cache" \
+               -H "Authorization: Bearer ${CLOUDFLARE_CACHEPURGE_TOKEN}" \
+               -H "Content-Type: application/json" \
+               --data '{"purge_everything":true}'
